version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/web/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      intervale: "weekly"
